-- Local/demo seed no longer inserts fictional SAMPLE consumer programs.
-- The production catalog is imported from data/programs via:
--
--   npm run import:programs
--
-- Automated tests keep SAMPLE fixtures local to lib/eligibility/__tests__.
-- Do not reintroduce SAMPLE: rows into this file.
